language: bash
services: docker
install:
  - docker build -t moodle-exttests .

script:
  - "docker run --name test0 -d -p 8000:80 moodle-exttests"
  - curl --fail -L http://127.0.0.1:8000/test_redir.php
after_failure:
  - docker logs test0
after_script:
  - docker rm -f test0
